# Generated by Django 3.1.7 on 2021-02-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20210228_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
